// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Copy

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float3> Target;
StructuredBuffer<float3> Source;
int N;
int index(int x, int y){
    return (x) + (y) *(N);
    }
[numthreads(8, 8, 1)]
void Copy (uint3 id : SV_DispatchThreadID)
{
    Target[index(id.x, id.y)] = Source[index(id.x, id.y)];
}
