// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Copy

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float3> Target;
StructuredBuffer<float3> Source;
int N;
int index(int x, int y, int z){
    return (x) + (y) * (N) + z * N * N;
    }
[numthreads(8, 8, 8)]
void Copy (uint3 id : SV_DispatchThreadID)
{
    Target[index(id.x, id.y, id.z)] = Source[index(id.x, id.y, id.z)];
}
