// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel RenderizeDensity

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture3D<float3> Target;
StructuredBuffer<float3> Source;
int N;

int index(int x, int y, int z){
    return x + (y * N) + (z * N * N);
    }
[numthreads(8, 8, 8)]
void RenderizeDensity (uint3 id : SV_DispatchThreadID)
{
    Target[id.xyz] = Source[index(id.x, id.y, id.z)];
}
