// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel RenderizeDensity

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float3> Target;
StructuredBuffer<float3> Source;
int N;

int index(int x, int y){
    return (x) + (y) *(N);
    }
[numthreads(8, 8, 1)]
void RenderizeDensity (uint3 id : SV_DispatchThreadID)
{
    Target[id.xy] = Source[index(id.x, id.y)];
}
