#pragma kernel Solve

RWStructuredBuffer<float3> Solution;
StructuredBuffer<float3> X;
StructuredBuffer<float3> X0;
float A;
float C;
int N;

int index(int x, int y, int z) {
    return x + (y * N) + (z * N * N);
}

[numthreads(8, 8, 8)]
void Solve(uint3 id : SV_DispatchThreadID) {
    float cRecip = 1.0f / C;
    float3 q0C = X0[index(id.x, id.y, id.z)];
    float3 qRight = float3(0,0,0), qLeft = float3(0,0,0);
    float3 qTop = float3(0,0,0), qBottom = float3(0,0,0);
    float3 qFront = float3(0,0,0), qBack = float3(0,0,0);

    if (id.x + 1 < N) qRight  = X[index(id.x + 1, id.y, id.z)];
    if (id.x > 0)     qLeft   = X[index(id.x - 1, id.y, id.z)];
    if (id.y + 1 < N) qTop    = X[index(id.x, id.y + 1, id.z)];
    if (id.y > 0)     qBottom = X[index(id.x, id.y - 1, id.z)];
    if (id.z + 1 < N) qFront  = X[index(id.x, id.y, id.z + 1)];
    if (id.z > 0)     qBack   = X[index(id.x, id.y, id.z - 1)];

    Solution[index(id.x, id.y, id.z)] =
        (q0C + A * (qRight + qLeft + qTop + qBottom + qFront + qBack)) * cRecip;
}